version: '3'

services:
  postgres:
    build: .
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    volumes:
      - ./volumes/postgres:/var/lib/postgreql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kuluya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
